# Generated by Django 4.1.3 on 2022-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='image',
            field=models.ImageField(default=1, upload_to='%Y-%m-%d'),
            preserve_default=False,
        ),
    ]
